vich_uploader:
    db_driver: orm

    mappings:
        categories:
            uri_prefix: /upload/images/category
            upload_destination: '%kernel.project_dir%/public/upload/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
