app_store:
    resource: '../src/Controller/Api/StoreController.php'
    type: attribute

app_admin:
    resource: '../src/Controller/Admin/'
    type: attribute

app_front:
    resource: '../src/Controller/Front'
    type: attribute
